package domain.model

import org.jetbrains.compose.resources.DrawableResource

enum class CurrencyCode(
    val country: String,
    val flag: DrawableResource
) {

    /* All commented classes are crypto currency

    //    ADA("Cardano", Res.drawable.ada),
    AED("United Arab Emirates", Res.drawable.aed),
    AFN("Afghanistan", Res.drawable.afn),
    ALL("Albania", Res.drawable.all),
    AMD("Armenia", Res.drawable.amd),
    ANG("Netherlands Antilles", Res.drawable.ang),
    AOA("Angola", Res.drawable.aoa),
//    ARB("Arbitrum", Res.drawable.arb),
    ARS("Argentina", Res.drawable.ars),
    AUD("Australia", Res.drawable.aud),
//    AVAX("Avalanche", Res.drawable.avax),
    AWG("Aruba", Res.drawable.awg),
    AZN("Azerbaijan", Res.drawable.azn),
    BAM("Bosnia and Herzegovina", Res.drawable.bam),
    BBD("Barbados", Res.drawable.bbd),
    BDT("Bangladesh", Res.drawable.bdt),
    BGN("Bulgaria", Res.drawable.bgn),
    BHD("Bahrain", Res.drawable.bhd),
    BIF("Burundi", Res.drawable.bif),
    BMD("Bermuda", Res.drawable.bmd),
//    BNB("Binance Coin", Res.drawable.bnb),
    BND("Brunei", Res.drawable.bnd),
    BOB("Bolivia", Res.drawable.bob),
    BRL("Brazil", Res.drawable.brl),
    BSD("Bahamas", Res.drawable.bsd),
//    BTC("Bitcoin", Res.drawable.btc),
    BTN("Bhutan", Res.drawable.btn),
    BWP("Botswana", Res.drawable.bwp),
    BYN("Belarus", Res.drawable.byn),
    BYR("Belarus (old)", Res.drawable.byr),
    BZD("Belize", Res.drawable.bzd),
    CAD("Canada", Res.drawable.cad),
    CDF("Congo-Kinshasa", Res.drawable.cdf),
    CHF("Switzerland", Res.drawable.chf),
    CLP("Chile", Res.drawable.clp),
    CNY("China", Res.drawable.cny),
    COP("Colombia", Res.drawable.cop),
    CRC("Costa Rica", Res.drawable.crc),
    CUC("Cuba", Res.drawable.cuc),
    CUP("Cuba", Res.drawable.cup),
    CVE("Cape Verde", Res.drawable.cve),
    CZK("Czech Republic", Res.drawable.czk),
//    DAI("Dai", Res.drawable.dai),
    DJF("Djibouti", Res.drawable.djf),
    DKK("Denmark", Res.drawable.dkk),
    DOP("Dominican Republic", Res.drawable.dop),
//    DOT("Polkadot", Res.drawable.dot),
    DZD("Algeria", Res.drawable.dzd),
    EGP("Egypt", Res.drawable.egp),
    ERN("Eritrea", Res.drawable.ern),
    ETB("Ethiopia", Res.drawable.etb),
//    ETH("Ethereum", Res.drawable.eth),
    EUR("Euro", Res.drawable.eur),
    FJD("Fiji", Res.drawable.fjd),
    FKP("Falkland Islands", Res.drawable.fkp),
    GBP("United Kingdom", Res.drawable.gbp),
    GEL("Georgia", Res.drawable.gel),
    GGP("Guernsey", Res.drawable.ggp),
    GHS("Ghana", Res.drawable.ghs),
    GIP("Gibraltar", Res.drawable.gip),
    GMD("Gambia", Res.drawable.gmd),
    GNF("Guinea", Res.drawable.gnf),
    GTQ("Guatemala", Res.drawable.gtq),
    GYD("Guyana", Res.drawable.gyd),
    HKD("Hong Kong", Res.drawable.hkd),
    HNL("Honduras", Res.drawable.hnl),
    HRK("Croatia", Res.drawable.hrk),
    HTG("Haiti", Res.drawable.htg),
    HUF("Hungary", Res.drawable.huf),
    IDR("Indonesia", Res.drawable.idr),
    ILS("Israel", Res.drawable.ils),
    IMP("Isle of Man", Res.drawable.imp),
    INR("India", Res.drawable.inr),
    IQD("Iraq", Res.drawable.iqd),
    IRR("Iran", Res.drawable.irr),
    ISK("Iceland", Res.drawable.isk),
    JEP("Jersey", Res.drawable.jep),
    JMD("Jamaica", Res.drawable.jmd),
    JOD("Jordan", Res.drawable.jod),
    JPY("Japan", Res.drawable.jpy),
    KES("Kenya", Res.drawable.kes),
    KGS("Kyrgyzstan", Res.drawable.kgs),
    KHR("Cambodia", Res.drawable.khr),
    KMF("Comoros", Res.drawable.kmf),
    KPW("North Korea", Res.drawable.kpw),
    KRW("South Korea", Res.drawable.krw),
    KWD("Kuwait", Res.drawable.kwd),
    KYD("Cayman Islands", Res.drawable.kyd),
    KZT("Kazakhstan", Res.drawable.kzt),
    LAK("Laos", Res.drawable.lak),
    LBP("Lebanon", Res.drawable.lbp),
    LKR("Sri Lanka", Res.drawable.lkr),
    LRD("Liberia", Res.drawable.lrd),
    LSL("Lesotho", Res.drawable.lsl),
//    LTC("Litecoin", Res.drawable.ltc),
    LTL("Lithuania", Res.drawable.ltl),
    LVL("Latvia", Res.drawable.lvl),
    LYD("Libya", Res.drawable.lyd),
    MAD("Morocco", Res.drawable.mad),
//    MATIC("Polygon", Res.drawable.matic),
    MDL("Moldova", Res.drawable.mdl),
    MGA("Madagascar", Res.drawable.mga),
    MKD("North Macedonia", Res.drawable.mkd),
    MMK("Myanmar", Res.drawable.mmk),
    MNT("Mongolia", Res.drawable.mnt),
    MOP("Macau", Res.drawable.mop),
    MRU("Mauritania", Res.drawable.mru),
    MUR("Mauritius", Res.drawable.mur),
    MVR("Maldives", Res.drawable.mvr),
    MWK("Malawi", Res.drawable.mwk),
    MXN("Mexico", Res.drawable.mxn),
    MYR("Malaysia", Res.drawable.myr),
    MZN("Mozambique", Res.drawable.mzn),
    NAD("Namibia", Res.drawable.nad),
    NGN("Nigeria", Res.drawable.ngn),
    NIO("Nicaragua", Res.drawable.nio),
    NOK("Norway", Res.drawable.nok),
    NPR("Nepal", Res.drawable.npr),
    NZD("New Zealand", Res.drawable.nzd),
    OMR("Oman", Res.drawable.omr),
//    OP("Optimism", Res.drawable.op),
    PAB("Panama", Res.drawable.pab),
    PEN("Peru", Res.drawable.pen),
    PGK("Papua New Guinea", Res.drawable.pgk),
    PHP("Philippines", Res.drawable.php),
    PKR("Pakistan", Res.drawable.pkr),
    PLN("Poland", Res.drawable.pln),
    PYG("Paraguay", Res.drawable.pyg),
    QAR("Qatar", Res.drawable.qar),
    RON("Romania", Res.drawable.ron),
    RSD("Serbia", Res.drawable.rsd),
    RUB("Russia", Res.drawable.rub),
    RWF("Rwanda", Res.drawable.rwf),
    SAR("Saudi Arabia", Res.drawable.sar),
    SBD("Solomon Islands", Res.drawable.sbd),
    SCR("Seychelles", Res.drawable.scr),
    SDG("Sudan", Res.drawable.sdg),
    SEK("Sweden", Res.drawable.sek),
    SGD("Singapore", Res.drawable.sgd),
    SHP("Saint Helena", Res.drawable.shp),
    SLL("Sierra Leone", Res.drawable.sll),
//    SOL("Solana", Res.drawable.sol),
    SOS("Somalia", Res.drawable.sos),
    SRD("Suriname", Res.drawable.srd),
    STN("Sao Tome and Principe", Res.drawable.stn),
    SVC("El Salvador", Res.drawable.svc),
    SYP("Syria", Res.drawable.syp),
    SZL("Eswatini", Res.drawable.szl),
    THB("Thailand", Res.drawable.thb),
    TJS("Tajikistan", Res.drawable.tjs),
    TMT("Turkmenistan", Res.drawable.tmt),
    TND("Tunisia", Res.drawable.tnd),
    TOP("Tonga", Res.drawable.top),
    TRY("Turkey", Res.drawable.try_currency),
    TTD("Trinidad and Tobago", Res.drawable.ttd),
    TWD("Taiwan", Res.drawable.twd),
    TZS("Tanzania", Res.drawable.tzs),
    UAH("Ukraine", Res.drawable.uah),
    UGX("Uganda", Res.drawable.ugx),
    USD("United States", Res.drawable.usd),
//    USDC("USD Coin", Res.drawable.usdc),
//    USDT("Tether", Res.drawable.usdt),
    UYU("Uruguay", Res.drawable.uyu),
    UZS("Uzbekistan", Res.drawable.uzs),
    VEF("Venezuela (Old)", Res.drawable.vef),
    VES("Venezuela", Res.drawable.ves),
    VND("Vietnam", Res.drawable.vnd),
    VUV("Vanuatu", Res.drawable.vuv),
    WST("Samoa", Res.drawable.wst),
    XAF("Central African CFA Franc", Res.drawable.xaf),
    XAG("Silver Ounce", Res.drawable.xag),
    XAU("Gold Ounce", Res.drawable.xau),
    XCD("East Caribbean Dollar", Res.drawable.xcd),
    XDR("Special Drawing Rights", Res.drawable.xdr),
    XOF("West African CFA Franc", Res.drawable.xof),
//    XPD("Palladium Ounce", Res.drawable.xpd),
    XPF("CFP Franc", Res.drawable.xpf),
//    XPT("Platinum Ounce", Res.drawable.xpt),
//    XRP("Ripple", Res.drawable.xrp),
    YER("Yemen", Res.drawable.yer),
    ZAR("South Africa", Res.drawable.zar),
    ZMK("Zambia (Old)", Res.drawable.zmk),
    ZMW("Zambia", Res.drawable.zmw),
    ZWL("Zimbabwe", Res.drawable.zwl)

     */

}